In [1]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.preprocessing import OneHotEncoder
from sklearn.cluster import KMeans
import math
from numpy import dot
from numpy.linalg import norm

In [3]:
row_data = [
  [
    '113082415690584490861', '25',        '/m/0403l3g',
    '/m/02ntfj',             '/m/025zzc', '/m/0bzvm2',
    '/m/028sqc',             '/m/04rlf',  '/m/064t9',
    '/m/01k8wb',             '/m/02vxn',  '/m/02jjt',
    '/m/01k8wb',             '/m/019_rr', '/m/028sqc',
    '/m/064t9',              '/m/04rlf',  '/m/01k8wb',
    '/m/07c1v',              '/m/019_rr', '/m/019_rr',
    '/g/120yrv6h',           '/m/019_rr', '/m/028sqc',
    '/m/04rlf',              '/m/04rlf',  '/m/028sqc',
    '/m/064t9',              '/m/04rlf',  '/m/064t9',
    '/m/028sqc',             '/m/019_rr', '/m/01k8wb',
    '/m/02vxn',              '/m/019_rr', '/m/02jjt',
    '/m/02jjt',              '/m/028sqc', '/m/04rlf',
    '/m/02vxn',              '/m/04rlf',  '/m/05rwpb',
    '/m/064t9',              '/m/028sqc', '/m/064t9',
    '/m/028sqc',             '/m/04rlf',  '/m/02jjt',
    '/m/019_rr',             '/m/02wbm',  '/m/019_rr',
    '/m/07c1v',              '/m/019_rr', '/m/01k8wb',
    '/m/07c1v',              '/m/01k8wb', '/m/019_rr',
    '/m/068hy',              '/m/019_rr', '/m/04rlf',
    '/m/028sqc',             '/m/064t9',  '/m/028sqc',
    '/m/064t9',              '/m/04rlf',  '/m/068hy',
    '/m/019_rr'
  ],
  [
    '115987064282754163674', '25',         '/m/02vxn',
    '/m/02jjt',              '/m/02ntfj',  '/m/025zzc',
    '/m/019_rr',             '/m/027x7n',  '/m/0403l3g',
    '/m/0bzvm2',             '/m/03hf_rm', '/m/025zzc',
    '/m/025zzc',             '/m/0bzvm2',  '/m/03hf_rm',
    '/m/0403l3g',            '/m/03hf_rm', '/m/0403l3g',
    '/m/025zzc',             '/m/02ntfj',  '/m/0bzvm2',
    '/m/04rlf',              '/m/028sqc',  '/m/05rwpb',
    '/m/06by7',              '/m/0glt670', '/m/02vxn',
    '/m/04rlf',              '/m/02jjt',   '/m/01k8wb',
    '/m/07c1v',              '/m/019_rr',  '/m/06ntj',
    '/m/02jjt',              '/m/019_rr',  '/m/01k8wb',
    '/m/07c1v',              '/m/0bzvm2',  '/m/0403l3g',
    '/m/03hf_rm',            '/m/025zzc',  '/m/02vxn',
    '/m/02jjt',              '/m/01k8wb',  '/m/098wr',
    '/m/02vxn',              '/m/02jjt',   '/m/019_rr',
    '/m/027x7n',             '/m/027x7n',  '/m/06ntj',
    '/m/019_rr',             '/m/01k8wb',  '/m/0bzvm2',
    '/m/0403l3g',            '/m/025zzc',  '/m/03hf_rm',
    '/m/02ntfj',             '/m/02jjt',   '/m/0f2f9',
    '/m/02vxn',              '/m/019_rr',  '/m/027x7n',
    '/m/0403l3g',            '/m/03hf_rm', '/m/025zzc',
    '/m/0bzvm2',             '/m/02jjt',   '/m/02vxn',
    '/m/025zzc',             '/m/03hf_rm', '/m/0bzvm2',
    '/m/0403l3g',            '/m/019_rr',  '/m/01k8wb',
    '/m/025zzc',             '/m/03hf_rm', '/m/0403l3g',
    '/m/0bzvm2',             '/m/02ntfj'
  ]
]

In [4]:
# 데이터 전처리

class DataPreprocessing(object):
   
    def ListToArray(self, row_data): 
        self.arr = np.array(row_data)
                                    
    def MakeColumns(self):
        self.user_id = []
        for i in range(self.arr.shape[0]):
            self.user_id.append(self.arr[i][0])
            
        self.channels = []
        for i in range(self.arr.shape[0]):
            self.channels.append(self.arr[i][1])
            
        self.cate = []
        for i in range(self.arr.shape[0]):
            self.cate.append(self.arr[i][2:])
    
    def ArrayToDataframe(self):
        self.row_df = pd.DataFrame({'Channels': self.channels, 'Category': self.cate}, index=self.user_id)
    
    def Extraction(self):
        self.category = []
        
        for i in range(self.row_df['Category'].shape[0]):
            np.array(pd.DataFrame(self.row_df['Category'][i]).value_counts()).reshape(1,-1)
            
            self.category_series = pd.DataFrame(self.row_df['Category'][i]).value_counts()
            
            self.df_category = pd.DataFrame(np.array(self.category_series).reshape(1, -1), 
                               columns = [j for j in self.category_series.index])

            self.category.append(self.df_category.sort_values(by=0, axis=1).iloc[0, -2:].index.tolist())
            
        self.first_category = pd.DataFrame(self.category)[0].str[0]
        self.second_category = pd.DataFrame(self.category)[1].str[0]
    
    def ToDf(self):
        df = pd.DataFrame({'channels': self.channels, 'first_category': self.first_category.values, 
                           'second_category': self.second_category.values}, index=self.user_id)
        
        return df

In [5]:
dt = DataPreprocessing()

In [6]:
dt.ListToArray(row_data)

/var/folders/0t/m5tmk07x1jn8mbwk5mpr748h0000gp/T/ipykernel_32550/950848848.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  self.arr = np.array(row_data)


In [7]:
dt.MakeColumns()
print(dt.user_id, dt.channels)

['113082415690584490861', '115987064282754163674'] ['25', '25']


In [8]:
dt.ArrayToDataframe()

In [9]:
dt.Extraction()
dt.category

[[('/m/04rlf',), ('/m/019_rr',)], [('/m/0403l3g',), ('/m/025zzc',)]]

In [10]:
df = dt.ToDf()
df

channels first_category second_category
113082415690584490861       25       /m/04rlf       /m/019_rr
115987064282754163674       25     /m/0403l3g       /m/025zzc

In [18]:
# sklearn의 cosine_similarity 사용
# 코사인 유사도 계산 시 시간복잡도 문제 해결

from sklearn.metrics.pairwise import cosine_similarity

class Classification(object):
    
    def __init__(self, df_data):
        self.df = df_data
    
    def Ohe(self, df): # 각 샘플에 대해 추출한 가장 선호하는 2개의 특성에 대해 원핫인코딩
        ohe = OneHotEncoder(sparse=False)
        self.train_feature = ohe.fit_transform(np.array(df[['first_category', 'second_category']]).reshape(-1,1))
    
    def makeData(self, channels):
        self.X_train = np.hstack((channels, np.array(cl.train_feature).reshape(2,-1)))
        
    def Kmeans(self): # k_means 클러스터링
        model = KMeans(n_clusters=2)
        model.fit(self.X_train)
        return np.array(model.predict(self.X_train))
    
    def ReturnResult_cosine_similarity(self, k=1):
        
        k_users = np.empty((0,k))
        for i in range(0, self.X_train.shape[0]):
            distance = [cosine_similarity(self.X_train[i].reshape(1,-1), self.X_train)]
            
            # i 번째 데이터 포인터와 다른 데이터들 사이의 거리를 작은순으로 정렬한 후 해당 인덱스를 이용해서 가장 가까운 k명의 이용자 선별
            distance_idx = np.array(distance).ravel().argsort()
            k_users = np.append(k_users, [distance_idx[:k]], axis=0)
                    
        return k_users

In [19]:
cl = Classification(df)

In [20]:
cl.Ohe(df)
cl.train_feature

array([[0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]])

In [21]:
cl.makeData(np.array(dt.channels).reshape(2, -1))

In [22]:
cl.X_train

array([['25', '0.0', '0.0', '0.0', '1.0', '1.0', '0.0', '0.0', '0.0'],
       ['25', '0.0', '0.0', '1.0', '0.0', '0.0', '1.0', '0.0', '0.0']],
      dtype='<U32')

In [23]:
result = cl.Kmeans()
result

array([0, 1], dtype=int32)

In [24]:
k_users = cl.ReturnResult_cosine_similarity()

In [25]:
k_users

array([[1.],
       [0.]])